on:
  pull_request:
    branches:
      - main
    types:
      - labeled

jobs:
  add-github-check:
    runs-on: ubuntu-latest

    steps:
      - name: Send a comment
        uses: JoseThen/comment-pr@v1.1.1
        with:
          comment: "Adding a Check because of the label"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add check
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: {{ secrets.GITHUB_TOKEN }}
          name: "Test that this works"
          status: "queued"
